name: build-project
run-name: Building the project
on:
  push:
    branches: [ main ]
env: 
  CARGO_TERM_COLOR: always
jobs:
  build-project:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.0
      - run: cd ${{ github.workspace }}
      - run: ls -la
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v2
        with: 
          name: nutctl
          path: |
            ./target/debug/nutctl
            ./target/debug/nutctl.d
      - name: Build for release
        run: cargo build --release
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            LICENSE
            ./target/release/nutctl
